language: generic

sudo: required

services:
  - docker

install:
  - docker info
  - cat /proc/sys/kernel/core_pattern
  - docker build -t logbt-precise -f Dockerfile.ubuntu-precise .

script:
  - sudo ./bin/logbt --setup
  - docker run logbt-precise
  - cat /proc/sys/kernel/core_pattern
